# Vendored dhat heap-profile viewer.
#
# The dhat-rs crate ships a static (HTML + JS + CSS) viewer for the
# `dhat-heap.json` profile files generated by `dhat::Profiler`.  Upstream
# hosts the same files on github.io for convenience, but the page is
# purely client-side — no upload happens; the JSON loads via a local
# `<input type="file">`.  Vendoring lets operators load profiles
# entirely off the public internet.
#
# Drops the three viewer files into `$out/share/dh_view/`.  The
# `dh-view` wrapper script in `$out/bin/` prints the absolute path to
# the HTML file, so an operator on a host with profiling enabled can do:
#
#   $ open "$(dh-view)"
#
# and inspect a profile produced by the locally-running log-processor.
{ lib
, stdenv
, fetchFromGitHub
, makeWrapper
, writeShellScript
}:

stdenv.mkDerivation {
  pname = "dh_view";
  # No upstream version on the viewer itself; pin to the commit that last
  # touched `dh_view/` in the github.io source repo.
  version = "2021-01-13";

  # The dhat-rs crate's repo doesn't contain the viewer — it lives in the
  # author's personal github.io source repo, served as static pages at
  # https://nnethercote.github.io/dh_view/.
  src = fetchFromGitHub {
    owner = "nnethercote";
    repo = "nnethercote.github.io";
    rev = "208f25da6ccbaf8e77a14abac0e60755ff11166b";
    hash = "sha256-eysgbin9UwFNqRiXadWbTlynHIE8R+SrY2kssD9KF30=";
  };

  nativeBuildInputs = [ makeWrapper ];

  dontConfigure = true;
  dontBuild = true;

  installPhase = ''
    runHook preInstall

    mkdir -p $out/share/dh_view $out/bin
    cp dh_view/dh_view.html $out/share/dh_view/
    cp dh_view/dh_view.js   $out/share/dh_view/
    cp dh_view/dh_view.css  $out/share/dh_view/

    cat > $out/bin/dh-view <<EOF
    #!${stdenv.shell}
    echo "$out/share/dh_view/dh_view.html"
    EOF
    chmod +x $out/bin/dh-view

    runHook postInstall
  '';

  meta = {
    description = "Heap profile viewer for dhat-rs JSON outputs";
    longDescription = ''
      Static HTML/JS viewer for the `dhat-heap.json` files produced by
      the `dhat` Rust crate's heap profiler.  Bundled here so the
      profile can be inspected without loading the upstream
      github.io-hosted copy.
    '';
    homepage = "https://github.com/nnethercote/dhat-rs";
    license = lib.licenses.asl20;
    platforms = lib.platforms.all;
  };
}
